# Беремо офіційний Dart образ
FROM dart:stable

# Робоча директорія всередині контейнера
WORKDIR /app

# Копіюємо всі файли проєкту в контейнер
COPY . .

# Встановлюємо залежності Dart
RUN dart pub get

# Запускаємо сервер
CMD ["dart", "bin/server.dart"]
